### ISSUE TITLE
SoTA DL?

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#137]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

On line 15 you mention SoTA DL models. Please introduce the abbreviation SoTA before its first use.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/21175639/228638668-2e09bd9e-5a86-4de7-9d2d-adfcba5f0c7c.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233193752-b11b194c-c4ff-49b8-8e94-d944591ee768.png)
I followed this advice to use it with hyphens as adjective: https://writingexplained.org/state-of-the-art-vs-state-of-the-art
