### ISSUE TITLE
Inconsistent spelling

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#139]
Editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

On line 8 you write "multi-modal". Please be consistent and change to "multimodal".

<img width="813" alt="image" src="https://user-images.githubusercontent.com/21175639/228639535-d64650a4-3638-4bc9-8cff-e0d17164c751.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233194330-7e4f91f6-52a8-4064-b8cf-a7f519e391ce.png)

![image](https://user-images.githubusercontent.com/36483359/233194394-27a161d2-b19a-4ed4-b413-eb2f341f49be.png)

![image](https://user-images.githubusercontent.com/36483359/233194612-51186b92-f0ae-45f9-930f-c2227df3de2c.png)
