### ISSUE TITLE
Equation formatting

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#143]
This is an editorial comment on your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027).

The equations on lines 54-55 and on line 64 do not appear correctly. Please follow to [author guidelines](https://joss.readthedocs.io/en/latest/submitting.html) and use `$$` for equations that appear on a single line, or LaTeX:

> # Mathematics
>
> Single dollars ($) are required for inline mathematics e.g. $f(x) = e^{\pi/x}$
>
> Double dollars make self-standing equations:
>
> $$\Theta(x) = \left\{\begin{array}{l}
>0\textrm{ if } x < 0\cr
> 1\textrm{ else}
> \end{array}\right.$$
>
> You can also use plain \LaTeX for equations
> \begin{equation}\label{eq:fourier}
> \hat f(\omega) = \int_{-\infty}^{\infty} f(x) e^{i\omega x} dx
> \end{equation}
> and refer to \autoref{eq:fourier} from text.

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233198305-a1b0ab10-dcac-49a6-bbbe-a0a1762b1648.png)

![image](https://user-images.githubusercontent.com/36483359/233198512-932c8db2-2270-4355-89fc-4d6f9fd68deb.png)
