### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#146]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027). 

On line 91, the word "Weight" should probably be changed to "weight"?

<img width="805" alt="image" src="https://user-images.githubusercontent.com/21175639/228644840-b3840cb9-abb3-4b06-be04-f8391e5750c5.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
The Weight uncertainty in the neural network is(was) title of the paper, I kept only the reference, see:
![image](https://user-images.githubusercontent.com/36483359/233199424-5e85d3b2-f3e2-4ddc-9e78-b18b717b1402.png)
