### ISSUE TITLE
Missing '@' in reference

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#147]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027). 

Please fix the reference to Efficientnet on line 101:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/21175639/228645182-48068499-25c2-42f9-aa89-f36944d94df6.png">

**Comment by osorensen** [comment]
Also fix a similar issue on line 106:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/21175639/228645411-a2adb127-daaa-4909-9526-b846019a0e1c.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233202091-87e7d6ca-c17a-4fa8-8791-bbccfec951a8.png)

![image](https://user-images.githubusercontent.com/36483359/233202185-79da4cbb-9d7f-43d4-bf31-f9e775b5175f.png)
