### ISSUE TITLE
Keras citation

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#149]
This is an editorial comment to your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5027). 

Please update citation so Keras is cited properly, see https://keras.io/getting_started/faq/#how-should-i-cite-keras.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/21175639/228646199-511cf839-e510-4926-8b4e-1cea7bf50c08.png">

**Comment by 5uperpalo** [comment]
fixed in [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf)
![image](https://user-images.githubusercontent.com/36483359/233200797-0463f59d-7953-4a68-880a-5f57e2c50377.png)

![image](https://user-images.githubusercontent.com/36483359/233201018-238109cb-1488-4536-b5a9-7f5742c5cfe9.png)
