### ISSUE TITLE
Working with large datasets

### ISSUE THREAD

**Issue by thatalfredh** [jrzaurin/pytorch-widedeep#150]
Hi, how should we write a custom dataset / dataloader to work with this package if, say, we want to use Tabular, Image and Text altogether but we are not able to load them in memory at once?

I'm thinking it'd be something simple like passing the loader wrapping our dataset but it does not seem to be viable as the the internal implementation of Trainer and .fit method seems to expect np.array inputs already?

Thank you in advance for your response.

**Comment by jrzaurin** [comment]
travelling right now, Ill reply to this asap 🙂

**Comment by jrzaurin** [comment]
Hey @thatalfredh 

Yeah, the trainer expects arrays, the intention is to facilitate usability so that all the transformations happen inside, in particular the building of the `DataLoader` . We could:
1. Create a new Trainer class that would replicate completely the existing one (i.e. inheriting it) and simply over-write that method so that it takes a `DataLoader` object. Or
2.  Add the possibility of passing `DataLoader`s to the fit method.

The two have their complications. In particular, the library is expects to work with multimodal datasets of type `WideDeepDataset`. Therefore users would have to know themselves how to create `WideDeepDataset`. I mean, is not complex, we could document it well and simply expose/publish the class to the user. 

Let me know what you think

**Comment by thatalfredh** [comment]
A simpler WideDeepDataset without the LDS (which i assume won't be commonly used) sounds appropriate for even greater flexibility. It was also where I intuitively looked to (just like PyTorch ImageFolder + DataLoader for example) before realizing WideDeep Trainer expects arrays.

As for the `.fit()` method in [Trainer](https://github.com/jrzaurin/pytorch-widedeep/blob/74e9de1d8f24d0f4d126c1f123c1b8a48991fbc5/pytorch_widedeep/training/trainer.py), maybe we could just modify how `custom_dataloader` argument is handled?

**Comment by jrzaurin** [comment]
Hey @thatalfredh 

So this can take some time (not much, but given my volume of work it cannot happen in one or two days🙂).  I will look into it in the next following days.

Thanks!

**Comment by thatalfredh** [comment]
hey @jrzaurin,

It's no issue, I'd be happy to contribute as well once there is a more concrete view :-) 

Yeap, so i was using all 3 modalities - deep tab, text and image, using TabTransformer, BERT and ViT for a dataset of about 300K row. I definitely cannot load their processed arrays into memory, the same goes even for tensors which take up half the size of arrays by default. 

Hence, I was thinking about that loader which takes in the WideDeepDataset (given the whole `pd.DataFrame`  that specifies the image path or as separate arguments - `tabular`,`text`, `image_paths`) for the images to get read from disk and preprocessed on the fly based on batch size during training.

**Comment by jrzaurin** [comment]
ok, so this actually involves a lot of moving pieces, since this needs a dedicated `fit` method where the processing happens inside. Currently, the processing is implemented via the `preprocessing` module. So this requirements changes the default flow of the library. It also has a solution. I can create an experimentation module with a custom datalaoder and a corresponding trainer that will be very similar to the existing one but adjusted to this requirements. 

Let me think a bit more about it and I will post the tentative design here.

**Comment by kd1510** [comment]
FYI I've picked this up and should have a PR ready soon. Added features are extremely similar to what @jrzaurin has described above.

**Comment by jrzaurin** [comment]
Hi @thatalfredh 

Surely you are now in an entire different place 😄, since it took me an eternity, but if you are still interested, I coded a `load_from_folder` module that you can use to load data that does not fit in memory. 

If this is something you are still interested in, or is useful, please, have a look and let me know if there is anything you want to add. 

At the moment I do not have available a good dataset that combines tabular, images and text datasets where the images do not fit in memory. Therefore, if you had one and wanted to "take the module for a spin" would be great 

Thanks for opening the issue! I just wish I had had more time to finish this sooner

Cheers
