### ISSUE TITLE
Editorial comments in JOSS submission

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#156]
Dear @5uperpalo 

Thanks for addressing all the issues I raised about the paper. I have a few more based on a second reading of the revised paper, and this is the first one.

On lines 32-33, I suggest to remove the sentence underlined in red in this screenshot, because this is not very important information in a short paper describing the library:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/21175639/234361098-713c1ebd-8726-4668-af1e-85167678dd25.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment]
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).
![image](https://user-images.githubusercontent.com/36483359/234399071-b0350d91-291e-43ee-977e-8baa4b31cbf3.png)
