### ISSUE TITLE
Not Being able to reproduce Bert results

### ISSUE THREAD

**Issue by TheLegendAli** [jrzaurin/pytorch-widedeep#169]
Hi I tried to reproduce my results from my bert finetuning using this library. Unfortunately, I could not replicate my results, and the F1 score falls by half. I ran into the same issue trying to reproduce [this tutoria](https://towardsdatascience.com/fine-tuning-bert-for-text-classification-54e7df642894)l as well. 

here is a [colab notebook](https://colab.research.google.com/drive/1VVYAKbRyU3-9CTBYyLveQs6kAL5t7oFJ#scrollTo=6h77VUsERKOM) of what I did. 

Am I doing anything wrong?

Thanks in advance

**Comment by jrzaurin** [comment]
Hey @TheLegendAli thanks for opening the issue, I will look into it asap 🙂

**Comment by jrzaurin** [comment]
I think I know what might happen (bear in mind I looked in my phone and is 6:30am here in the London). I think you are passing `pred_dim = 2` while this is a binary classification problem and has to be equal to 1, look here: https://github.com/jrzaurin/pytorch-widedeep/blob/master/pytorch_widedeep/models/wide_deep.py#L86

To be honest we should be better/more explicit regarding this parameter, since I see how it can cause confusion. 

Anyway, let me know if this was the issue and thanks for opening it, I will add some warning in the next release.

**Comment by TheLegendAli** [comment]
Hi thanks for the feedback, that definitely did improve the results. However, there is still a wide difference in performance. I think I might be doing something else wrong. And I hope you had some coffee in the morning

**Comment by jrzaurin** [comment]
okay then, I'll check

**Comment by jrzaurin** [comment]
Hey @TheLegendAli , so, after a quick look my main comment would be that you need to make sure you are comparing the same thing, since at the moment this is not the case. 

For example, in one case you are using `bert-base-uncased` with a certain tokenizer set up, while in another case you are using `distilbert-base-uncased`. This should not really matter much, but is worth pointing out. 

Perhaps a more relevant aspect is the fact that in one case you are not freezing the model weights, resulting in you finetunning the model to the data. However, when using the library you are completely freezing the weights (by setting up `freeze_bert=True`). 

Let's do something, since you are in the [slack channel]([slack](https://join.slack.com/t/pytorch-widedeep/shared_invite/zt-soss7stf-iXpVuLeKZz8lGTnxxtHtTw)) let's close the issue and move the conversation there :) 

Thanks for opening it!
