### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xylovezxy** [jrzaurin/pytorch-widedeep#222]
Hi，Sorry to bother you again.
I previously raised a question with you. I want to use clip as a model for both text and image ends, and then use a certain dataset for binary classification. Following your guidance, I will write and inherit the clip model into the BaseWDModelComponen class. But clip needs to process the image data into tensors for training, which caused me to encounter the following error when running trainer.fit:
![image](https://github.com/user-attachments/assets/30ba9afd-a16b-4dcf-98dc-6a6c336ebaa0)
I tried to change the _prepare_images function in w_d_dataset.cy to directly return xdi when xdi is a Tensor, but it didn't work.
I have also tried using only clip to extract features and then adding them to our dataframe for training with widedeep, but the results were mediocre.
If you could give me some advice, I would greatly appreciate it！

**Comment by jrzaurin** [comment]
Hey @xylovezxy 

no worries, you do not bother me. However, the way you share your errors makes it really hard for me to help since the only approach is mostly a guess-work

The issue there is that `pytorch-widedeep` is designed to work with arrays as inputs all across the library and changing that is not really that simple. 

One thing you could do is the following: the `fit` method in the `Trainer` allows you to pass a `custom_dataloader`. See all the code [here](https://github.com/jrzaurin/pytorch-widedeep/blob/deb4f2e2f156af654ec5a22705a812105b16e995/pytorch_widedeep/training/trainer.py#L456C1-L469C3)

You can code your dataloader and adjust that code accordingly. Otherwise, if you join the slack channel we can pair at some time and I can try to help you :)

**Comment by jrzaurin** [comment]
Hey @xylovezxy what I mean is that, without code and data to reproduce your error, it is complex to provide a good answer. 

The whole library is designed to take arrays and the tensor transformation happens internally via the a custom Dataset class, as you know: `WideDeepDataset`.

Now, inside the `fit` method in the Trainer, I call a function called `wd_train_val_split` which you can see here: https://github.com/jrzaurin/pytorch-widedeep/blob/deb4f2e2f156af654ec5a22705a812105b16e995/pytorch_widedeep/training/_trainer_utils.py#L114

this function will return two arrays (potentially, one of the is Optional), `train_set` and `eval_set`. These are then pass to a simple `DataLoader` class unless  a `custom_dataloader` is used, See here: https://github.com/jrzaurin/pytorch-widedeep/blob/deb4f2e2f156af654ec5a22705a812105b16e995/pytorch_widedeep/training/trainer.py#L470 . But even in this case, it still expects arrays.

In other words, the `fit` method IS NOT design to take Tensors. To do so we would have to code a new method where it takes tensors. This can be done, but is quite a bit of work. For example, this would require a fit method that would look like:

```python
   @alias("finetune", ["warmup"])
    def fit(  
        self,
        X_wide: Optional[Tensor] = None,
        X_tab: Optional[Tensor] = None,
        X_text: Optional[Union[Tensor, List[Tensor]]] = None,
        X_img: Optional[Union[Tensor, List[Tensor]]] = None,
        X_train: Optional[Dict[str, Union[Tensor, List[Tensor]]]] = None,
        X_val: Optional[Dict[str, Union[Tensor, List[Tensor]]]] = None,
        val_split: Optional[float] = None,
        target: Optional[Tensor] = None,
        n_epochs: int = 1,
        validation_freq: int = 1,
        batch_size: int = 32,
        custom_dataloader: Optional[DataLoader] = None,
        feature_importance_sample_size: Optional[int] = None,
        finetune: bool = False,
        with_lds: bool = False,
        **kwargs,
    ):
    ...
```

Then internally we could have a class like

```python
class WideDeepDatasetTensor(Dataset):
    def __init__(
        self,
        X_wide: Optional[Tensor] = None,
        X_tab: Optional[Tensor] = None,
        X_text: Optional[Union[Tensor, List[Tensor]]] = None,
        X_img: Optional[Union[Tensor, List[Tensor]]] = None,
        target: Optional[Tensor] = None,
        transforms: Optional[Union[Transforms, Compose]] = None,
        is_training: bool = True,
    ):
    ...
```

and also propagate the changes accordingly, since this would affect to almost every single method of the trainer (`predict`, etc)

as you can see, is ....a lot of work

**Comment by xylovezxy** [comment]
Okay, thank you. I may consider giving up on my idea

**Comment by xylovezxy** [comment]
How can the training process be accelerated on GPU if you use numpy arrays as input?

**Comment by jrzaurin** [comment]
The transformation to Tensors happens inside the `Trainer`
