### ISSUE TITLE
how to save/load "preprocess_deep" and "preprocess_wide"

### ISSUE THREAD

**Issue by AITutorials** [jrzaurin/pytorch-widedeep#29]
when I use `joblib` to `dump` the preprocess_deep and preprocess_wide: 

```
from joblib import dump, load
...

# deepdense
preprocess_deep = DensePreprocessor(embed_cols=embed_cols, continuous_cols=cont_cols)
X_deep = preprocess_deep.fit_transform(df_train)

# dump my preprocess_deep
dump(preprocess_deep, 'preprocess_deep.pkl')

deepdense = DeepDense(
    hidden_layers=[64, 32],
    deep_column_idx=preprocess_deep.deep_column_idx,
    embed_input=preprocess_deep.embeddings_input,
    continuous_cols=cont_cols,
)

...

preprocess_deep = load("preprocess_deep.pkl")
X_deep_te = preprocess_deep.transform(df_test)
```

---

error:

Traceback (most recent call last):
  File "wide_deep_baseline_train.py", line 90, in <module>
    X_deep_te = preprocess_deep.transform(df_test)
  File "/usr/local/lib/python3.7/site-packages/pytorch_widedeep/preprocessing/_preprocessors.py", line 273, in transform
    df_emb = self.label_encoder.transform(df_emb)
  File "/usr/local/lib/python3.7/site-packages/pytorch_widedeep/utils/dense_utils.py", line 98, in transform
    df_inp[k] = df_inp[k].apply(lambda x: v[x])
  File "/usr/local/lib64/python3.7/site-packages/pandas/core/series.py", line 4200, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2402, in pandas._libs.lib.map_infer
  File "/usr/local/lib/python3.7/site-packages/pytorch_widedeep/utils/dense_utils.py", line 98, in <lambda>
    df_inp[k] = df_inp[k].apply(lambda x: v[x])
KeyError: nan

**Comment by jrzaurin** [comment]
Hi @AITutorials 

The error you are getting happens here:
https://github.com/jrzaurin/pytorch-widedeep/blob/9f610513670da8ab670047ea3f3a94f5769c31d7/pytorch_widedeep/preprocessing/_preprocessors.py#L273

when you run `transform` with the trained `label_encoder`, as you can see here: 
https://github.com/jrzaurin/pytorch-widedeep/blob/9f610513670da8ab670047ea3f3a94f5769c31d7/pytorch_widedeep/utils/dense_utils.py#L98

This is because you have `nan`s in your `df_test` data, and no categorical encoding was built for `nan`, which is ok. You need to clean your data first (as the `preprocessor` does not handle `nan` by default. Whatever one wants to do with `nan`s is a user decision). 

your options are two: 

1. replace `nan` with a new category (e.g. `"unknown"`) AND THEN train the encoder (preferred) 

```python
df_train = df_train.fillna('unknown')
preprocess_deep = DensePreprocessor(embed_cols=embed_cols, continuous_cols=cont_cols)
# "unknown" will be a new category/label
X_deep = preprocess_deep.fit_transform(df_train)

# dump my preprocess_deep
dump(preprocess_deep, 'preprocess_deep.pkl')

# load
preprocess_deep = load("preprocess_deep.pkl")
df_test = df_test.fillna('unknown')
X_deep_te = preprocess_deep.transform(df_test)
```

2. replace `nan` on the test dataset directly and then, the trained encoder will encode any unseen category as `"unseen"`

```python
preprocess_deep = DensePreprocessor(embed_cols=embed_cols, continuous_cols=cont_cols)
X_deep = preprocess_deep.fit_transform(df_train)

# dump my preprocess_deep
dump(preprocess_deep, 'preprocess_deep.pkl')

# load
preprocess_deep = load("preprocess_deep.pkl")
df_test = df_test.fillna('unknown')
# because "unknown" will have not been seen before, it will be assigned the label of the "unseen" category
X_deep_te = preprocess_deep.transform(df_test)
```
