### ISSUE TITLE
Computation of AUROC at the epoch end

### ISSUE THREAD

**Issue by rv-iiita** [jrzaurin/pytorch-widedeep#79]
Hey , I was implementing this binary classification on adult census dataset using pytorch-widedeep  in which I am trying to calculate AUROC metric using **torchmetric's AUROC** at the epoch's end  but i am getting this error , 

`trainer = Trainer(model, objective="binary", metrics=[AUROC])`
`trainer.fit( X_wide=X_wide, X_tab=X_tab, target=target, n_epochs=5, batch_size=64, val_split=0.2 )`
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Looking for help regarding this . 

Thank you, awesome library

**Comment by jrzaurin** [comment]
Hey @rv-iiita 

do you have some code we could reproduce? 

Other than that I have an idea what it might be, which is `AUROC` needs to be instantiated? i.e. `AUROC()`

Let me check with @5uperpalo anyway and get back to you

**Comment by rv-iiita** [comment]
Yes sir @jrzaurin, here i am attaching the link to Google colab notebook of the code

[https://colab.research.google.com/drive/1h0-6wTEcVh951KErleCBKvN6X_g5-LMA?usp=sharing](url)

**Comment by jrzaurin** [comment]
Thanks!

more news soon 😉

**Comment by 5uperpalo** [comment]
hi @rv-iiita , 
this issue was reported and fixed previously, see pullrequest : https://github.com/jrzaurin/pytorch-widedeep/commit/8b4c3a8acbf06b385c821d7111b1139a16b4f480
* **problem (with an excuse O:-) )**: pytorch_widedeep version on pip is 1.0.13, last version on git is 1.0.14, we are in the middle of merging a large pull request and we were hoping to do it much sooner so the v1.0.14 was not pushed to pip as were hoping to push just a new version (it might take couple of additional days to merge all the new code...)
* **solution** : please install the last version from git (git clone xxx), in attached screenshot you may see it worked locally on my laptop when I install the library from git
![image](https://user-images.githubusercontent.com/36483359/156050522-76ee363d-6284-4c3e-a70b-9252eed897a6.png)

* **solution** @jrzaurin : please push the v1.0.14 to pip :) and I will do my best to finalize my work on the last pull request (again might take couple of days including code review...)

**Comment by rv-iiita** [comment]
Thanks a lot @jrzaurin  & @5uperpalo for our kind help 😊 !!
