### ISSUE TITLE
Model pretraining

### ISSUE THREAD

**Issue by ahmed-mohamed-sn** [jrzaurin/pytorch-widedeep#86]
Great package. Is it possible to pretrain models on unlabeled data?

**Comment by jrzaurin** [comment]
hey @ahmed-mohamed-sn 

Thanks for the comment. If you mean, self-supervised, no, at the moment the library can only be used for supervised problems, sorry 🙂.

We aim to bring self-supervised (actually a couple of approaches) in v2, but for the time being we only support supervised problems. 

v2 should be out in the next few months. 

You could join our slack channel and be up to date if you wanted 🙂.

**Comment by ahmed-mohamed-sn** [comment]
Yes indeed I meant self-supervised learning. Looking forward to start using v2 👍🏼 

What is your slack channel?

**Comment by jrzaurin** [comment]
Hey @ahmed-mohamed-sn here you have the link Join my Slack workspace! https://join.slack.com/t/pytorch-widedeep/shared_invite/zt-soss7stf-iXpVuLeKZz8lGTnxxtHtTw

**Comment by jrzaurin** [comment]
hi @ahmed-mohamed-sn 

I posted this yesterday in the slack channel, but I dont know if you are there:

-------------------------------------------------------------------------------
hi guys
so, next week we will release v 1.2 of the library. There are number of features coming, but perhaps the most important one is the ability to run self-supervised pre-training for all tabular models (with the exception of the Tab-Perceiver) via two processes or techniques: Encoder-Decoder (as in TabNet) and Contrastive-Denoising (as in SAINT). This functionality has proven to be useful when datasets are small, but it is also useful if you are faced with a problem that is unsupervised and you need to compute numerical encodings of your features, for example. If you have any questions, please, let me know.

Until the official release you can install the version 1.2 from the branch itself as:

pip install git+https://github.com/jrzaurin/pytorch-widedeep.git@base_trainer_and_self_supervised

and you have full examples in the examples folder and here:

https://github.com/jrzaurin/pytorch-widedeep/blob/base_trainer_and_self_supervised/examples/scripts/adult_census_cont_den_full_example.py

https://github.com/jrzaurin/pytorch-widedeep/blob/base_trainer_and_self_supervised/examples/scripts/adult_census_enc_dec_full_example.py

and docs:
https://pytorch-widedeep.readthedocs.io/en/base_trainer_and_self_supervised/index.html

Note that this is a crucial step to be able to run multimodal models (tabular, text and image) with all pre-trained weights. The library is integrated with the latest torchvision version, which allows to use many pre-trained models. You can now pre-train tabular models, and currently one could use pre-trained word vectors. Of course, one can see that the weakest mode, from a pre-train point of view, is text, since the library does not allow for fully pre-trained models (only word vectors) yet. This is why, while we will keep devoting some to tabular DL models (we intend to bring a couple more models and/or variants to existing models) the next stage of development will be integrating with the wonderful Hugginface library. Nonetheless, even now, one could use a custom Hugginface model and pass it to the WideDeep class. I will soon include a notebook showing how to do such a thing.  Note that, whether is now via a custom model, or in the future via our integration with Hugginface, at that point, all the weights from the model will start from a pre-trained step.

Anyway, official release of v1.2.0 next week and in the meantime, if you want to test the library, all code in that branch

--------------------------------------------------------------------------------
