### ISSUE TITLE
Support for multiple GPUs

### ISSUE THREAD

**Issue by heartkilla** [jrzaurin/pytorch-widedeep#92]
Is there any way to run the models on multiple GPUs?

**Comment by jrzaurin** [comment]
hey @heartkilla 

Thanks for asking

So, at the moment there is no support in the package as such. The reason is actually quite simple. Every test on GPU is run on my personal AWS account so I did not have the budget to develop full support for multiple-gpu. However this is changing soon and is in our road map. 

Nonetheless, I wonder if you could still use the library, or the code in it, to run models in multiple GPUs. For example, maybe you could use Data parallelism as:

```python
parallel_net = nn.DataParallel(my_widedeep_model, gpu_ids = [0,1,2])
```

and then train the model as usual either using the library or then building your own training loop. If you find some issues maybe post them here so that 1. we might be able to help and 2. they might help us as we include multiple GPU support

Let me know what you think and thanks again for opening the issue

**Comment by heartkilla** [comment]
@jrzaurin 
Thank you very much for your reply.

I'm trying to do a similar thing but it seems to change the attributes of the model, maybe there is some workaround?

```python
tab_mlp = TabMlp(
    column_idx=tab_preprocessor.column_idx,
    cat_embed_input=tab_preprocessor.cat_embed_input, 
    continuous_cols=continuous_cols
)
model = WideDeep(deeptabular=tab_mlp)

model = torch.nn.DataParallel(model)

trainer = Trainer(model, objective="mae")
```

```python
AttributeError: 'DataParallel' object has no attribute 'with_fds'
```

**Comment by heartkilla** [comment]
This helped👍

```python
class MyDataParallel(torch.nn.DataParallel):
    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.module, name)

model_parallel = MyDataParallel(model, device_ids=[0, 1])
```


https://discuss.pytorch.org/t/how-to-reach-model-attributes-wrapped-by-nn-dataparallel/1373/7
