### ISSUE TITLE
PyTorch Lightning Trainer

### ISSUE THREAD

**Issue by chris-boson** [jrzaurin/pytorch-widedeep#97]
related to https://github.com/jrzaurin/pytorch-widedeep/issues/92

Would it possible to make this library compatible with a standard training framework such as [PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/stable/)? It would offer
- Multi GPU support
- Compatibility with [`torchmetrics`](https://torchmetrics.readthedocs.io/en/stable/) (I found some issues with device placement when trying to use them)
- Easy integration with several logging frameworks (W&B, MLFlow, Neptune, etc.)
- Many other training optimizations offered by Lightning (16bit precision, TPU, optimized data loading etc.)
- Standard model and data structures (`LightningModule` and `LightningDataModule`)

**Comment by jrzaurin** [comment]
Hey @chris-boson 

Well, when I started to code the library my goal was to create a model reservoir and a frame to combine text, images and tabular in the simplest way. With that in mind I decided to not integrate with any other library simply because I left that responsibility to the user, and I did not want the user to have to learn about any additional library. Or perhaps simply reduce the number of extra-libraries that a user would have to know about. 

For example, one could create a model simply with my library and then use Lightning for the training process, this way accessing all the benefits from the library. One could easily code a Callback and integrate with MLFlow or RayTune, etc. 

If is helpful we might write a few notebooks to show it. 

Now, I am not opposed at all to a wholistic integration, but at this point is a lot of work. If you want to have a chat we can discuss the implications. Otherwise we will include those notebooks and we will help you use the library as much as we can! Advising as to how to integrate it with other libraries. 

In the  meantime, if you want to open an issue with the torchmetrics issues you are finding that would be great. 

Let me know your thoughts and thanks for opening the issue!
